gcloud:
  project: snappy-elf-384513
  bucket_name: processed-data-bucket
  cluster: cluster-66e3
  region: europe-west9

kafka:
  kafka_host:
    local: localhost:9092
    docker: kafka:29092

redis:
  host:
    local: localhost
    docker: redis